package pro;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JRadioButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.BevelBorder;
import java.awt.Rectangle;
import java.awt.Dimension;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tharuka
 */
public class reg extends javax.swing.JFrame {
	private ButtonGroup genderGroup; 
	private mainconnection connect;
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form reg
     */
	public reg() {
		getContentPane().setBackground(new Color(180, 241, 248));
        setPreferredSize(new Dimension(1850, 1270));
        initComponents();
        // Create an instance of mainconnection
        connect = new mainconnection();
        // Establish the database connection
        connect.establishConnection();
        new applicant(connect.getConnection());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    @SuppressWarnings("serial")
	private void initComponents() {
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBounds(261, 133, 474, 41);
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setBounds(261, 361, 474, 41);
        jTextField3 = new javax.swing.JTextField();
        jTextField3.setBounds(261, 209, 474, 41);
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setBounds(261, 490, 474, 41);
        jTextField8 = new javax.swing.JTextField();
        jTextField8.setBounds(261, 286, 474, 41);
        jButton1 = new javax.swing.JButton();
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 14));
        jButton1.setBounds(580, 697, 173, 61);
        jButton2 = new javax.swing.JButton();
        jButton2.setFont(new Font("Tahoma", Font.BOLD, 14));
        jButton2.setBounds(328, 697, 173, 61);
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton1.setFont(new Font("Tahoma", Font.BOLD, 14));
        jToggleButton1.setBounds(82, 697, 173, 61);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(113, 147, 37, 13);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(113, 223, 70, 13);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(113, 300, 70, 13);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(113, 375, 37, 13);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(113, 504, 80, 13);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("BACK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Contact");

        jLabel5.setText("E Mail");

        jLabel7.setText("NIC number");
        
        lblNewLabel = new JLabel("Document link");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 18));
        lblNewLabel.setBounds(57, 632, 173, 27);
        
        textField = new JTextField();
        textField.setBounds(257, 628, 478, 41);
        textField.setColumns(10);
        
        JLabel lblNewLabel_1 = new JLabel("For Document Submition");
        lblNewLabel_1.setBounds(288, 566, 309, 18);
        lblNewLabel_1.setFont(new Font("Arial Black", Font.BOLD, 18));
        
        JLabel lblNewLabel_2 = new JLabel("Gender");
        lblNewLabel_2.setBounds(113, 431, 45, 13);
        
        JRadioButton male = new JRadioButton("Male");
        male.setBounds(261, 427, 173, 21);
        male.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		gender="male";
        	}
        });
        
        JRadioButton female = new JRadioButton("Female");
        female.setBounds(506, 427, 184, 21);
        female.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		gender="female";
        	}
        	
        }); 
        genderGroup = new ButtonGroup();
        genderGroup.add(male);
        genderGroup.add(female);
        
        JButton btnNewButton = new JButton("SHOW DATA");
        btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 14));
        btnNewButton.setBounds(916, 697, 499, 61);
        btnNewButton.addActionListener(new ActionListener() {
        	
        	public void actionPerformed(ActionEvent e) {
                // Clear existing data from the table
                DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
                tblModel.setRowCount(0);

                // Make connection between DB and button
                mainconnection connect = new mainconnection();
                connect.establishConnection();

                // Data validation
                applicant tblshow = new applicant(connect.getConnection(), tblModel);
                
                // Call the tblshow method to populate the table
                tblshow.tblshow();
            }
        });
      
        btnNewButton.setBackground(new Color(255, 128, 128));
        
        table = new JTable();
        table.addAncestorListener(new AncestorListener() {
        	public void ancestorAdded(AncestorEvent event) {
        	}
        	public void ancestorMoved(AncestorEvent event) {
        	}
        	public void ancestorRemoved(AncestorEvent event) {
        	}
        });
        table.setCellSelectionEnabled(true);
        table.setBounds(new Rectangle(916, 133, 499, 525));
        table.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
        table.setName("");
        table.setToolTipText("local db table");
   

        DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
        tblModel.setColumnIdentifiers(new Object[]{"ApplicantId", "Name"});  // Set column headers

        table.setModel(tblModel);

        // Set font size for the table cells
        table.setFont(new Font("Arial", Font.PLAIN, 18));  // Adjust the font size as needed
        table.setRowHeight(25);  
        

        table.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"ApplicantId", "Name"
        	}
        ) {
        	@SuppressWarnings("rawtypes")
			Class[] columnTypes = new Class[] {
        		Integer.class, Object.class
        	};
        	@SuppressWarnings({ "rawtypes", "unchecked" })
			public Class getColumnClass(int columnIndex) {
        		return columnTypes[columnIndex];
        	}
        });
        table.getColumnModel().getColumn(0).setMinWidth(13);
        table.setBackground(new Color(255, 255, 255));
        
        JLabel lblNewLabel_3 = new JLabel("Applicant Id");
        lblNewLabel_3.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblNewLabel_3.setBounds(1003, 97, 115, 26);
        
        JLabel lblNewLabel_4 = new JLabel("Name");
        lblNewLabel_4.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblNewLabel_4.setBounds(1288, 104, 45, 13);
        getContentPane().setLayout(null);
        getContentPane().add(jToggleButton1);
        getContentPane().add(lblNewLabel_2);
        getContentPane().add(jLabel5);
        getContentPane().add(jLabel3);
        getContentPane().add(jLabel4);
        getContentPane().add(jLabel7);
        getContentPane().add(jLabel2);
        getContentPane().add(jButton2);
        getContentPane().add(lblNewLabel);
        getContentPane().add(textField);
        getContentPane().add(jTextField4);
        getContentPane().add(jTextField1);
        getContentPane().add(jTextField3);
        getContentPane().add(jTextField8);
        getContentPane().add(jTextField2);
        getContentPane().add(male);
        getContentPane().add(female);
        getContentPane().add(jButton1);
        getContentPane().add(btnNewButton);
        getContentPane().add(lblNewLabel_1);
        getContentPane().add(lblNewLabel_3);
        getContentPane().add(lblNewLabel_4);
        getContentPane().add(table);
        
        panel = new JPanel();
        panel.setBackground(new Color(0, 64, 128));
        panel.setBounds(0, 0, 1540, 74);
        getContentPane().add(panel);
                panel.setLayout(null);
        
                jLabel1 = new javax.swing.JLabel();
                jLabel1.setBounds(10, 10, 523, 64);
                panel.add(jLabel1);
                jLabel1.setForeground(new Color(128, 255, 255));
                jLabel1.setFont(new Font("Arial Black", Font.BOLD, 40));
                
                        jLabel1.setText("REGISTRATION FORM");

        pack();
    }// </editor-fold>                        

    
    //submit button performed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Get data from JTextFields
        String name = jTextField1.getText();
        String address = jTextField3.getText();
        String contactText = jTextField8.getText();
        String email = jTextField2.getText();
        String nicText = jTextField4.getText();
        String docLink = textField.getText();

        // Convert contactText and nicText to int
        int contact = 0;
        int nic = 0;

        try {
            contact = Integer.parseInt(contactText);
            nic = Integer.parseInt(nicText);
        } catch (NumberFormatException e) {
            // Handle the case where the text is not a valid integer
            JOptionPane.showMessageDialog(this, "Invalid contact number or NIC. Please enter valid integers.");
            return; // Exit the method to avoid proceeding with invalid data
        }

        // Insert data into the database using the applicant class
        applicant applicantHandler = new applicant(connect.getConnection());
        applicantHandler.insertData(name, address, contact, email, nic, docLink, gender);
    }


                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Clear button action
        // Display a confirmation dialog
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to clear the fields?", "Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Clear the fields
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField8.setText("");
            textField.setText("");

            // Deselect radio buttons
            
            genderGroup.clearSelection();}
           
    }
                           

    @SuppressWarnings("deprecation")
	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
home nw= new home();
nw.show();
dispose();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
   
    private JLabel lblNewLabel;
    private JTextField textField;
    private String gender;
    private JTable table;
    private JPanel panel;
	public JTable getTable() {
		return table;
	}
}